spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot_test?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: "123456"

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl